use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

/// A compliance profile entry in the index.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
pub struct ProfileEntry {
    /// Unique profile identifier (e.g., "mitre-rhel9-stig").
    pub id: String,
    /// Human-readable name.
    pub name: String,
    /// Source organization (mitre, dev-sec, gcp, custom).
    pub source: ProfileSource,
    /// Upstream git repository URL.
    pub upstream_url: String,
    /// Upstream git ref (tag, branch, commit).
    pub upstream_ref: String,
    /// Number of InSpec controls in the profile.
    pub control_count: usize,
    /// BLAKE3 hash of the profile directory.
    pub profile_hash: String,
    /// Which Pangea providers this profile applies to.
    pub applicable_providers: Vec<String>,
    /// NIST 800-53 control families covered.
    pub nist_families: Vec<String>,
    /// CIS benchmark IDs covered.
    pub cis_benchmarks: Vec<String>,
    /// Whether RSpec has been generated from this profile.
    pub rspec_generated: bool,
    /// When the profile was last synced from upstream.
    pub last_synced: Option<DateTime<Utc>>,
}

/// The source organization for a compliance profile.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq, Hash)]
#[serde(rename_all = "snake_case")]
pub enum ProfileSource {
    /// MITRE SAF profiles (STIG baselines, CIS benchmarks).
    Mitre,
    /// dev-sec.io hardening profiles.
    DevSec,
    /// Google Cloud Platform profiles.
    Gcp,
    /// CIS (Center for Internet Security) profiles.
    Cis,
    /// Custom, hand-written profiles.
    Custom,
    /// Auto-generated profiles (e.g., from Pangea DSL).
    AutoGenerated,
}

impl std::fmt::Display for ProfileSource {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Mitre => write!(f, "mitre"),
            Self::DevSec => write!(f, "dev-sec"),
            Self::Gcp => write!(f, "gcp"),
            Self::Cis => write!(f, "cis"),
            Self::Custom => write!(f, "custom"),
            Self::AutoGenerated => write!(f, "auto-generated"),
        }
    }
}

/// Summary statistics for a profile index.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
pub struct IndexStats {
    /// Total number of profiles in the index.
    pub total_profiles: usize,
    /// Total number of InSpec controls across all profiles.
    pub total_controls: usize,
    /// Number of profiles with RSpec tests generated.
    pub total_rspec_generated: usize,
    /// Unique providers covered across all profiles.
    pub providers_covered: Vec<String>,
    /// Unique NIST 800-53 families covered.
    pub nist_families_covered: Vec<String>,
}

impl IndexStats {
    /// Create empty statistics.
    #[must_use]
    pub fn empty() -> Self {
        Self {
            total_profiles: 0,
            total_controls: 0,
            total_rspec_generated: 0,
            providers_covered: Vec::new(),
            nist_families_covered: Vec::new(),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_entry() -> ProfileEntry {
        ProfileEntry {
            id: "test-profile".to_string(),
            name: "Test Profile".to_string(),
            source: ProfileSource::Custom,
            upstream_url: "https://github.com/example/test".to_string(),
            upstream_ref: "main".to_string(),
            control_count: 10,
            profile_hash: "abc123".to_string(),
            applicable_providers: vec!["aws".to_string()],
            nist_families: vec!["AC".to_string(), "CM".to_string()],
            cis_benchmarks: vec![],
            rspec_generated: false,
            last_synced: None,
        }
    }

    #[test]
    fn profile_entry_serde_roundtrip() {
        let entry = sample_entry();
        let json = serde_json::to_string(&entry).unwrap();
        let deserialized: ProfileEntry = serde_json::from_str(&json).unwrap();
        assert_eq!(entry, deserialized);
    }

    #[test]
    fn profile_entry_with_last_synced_serde_roundtrip() {
        let mut entry = sample_entry();
        entry.last_synced = Some(Utc::now());
        let json = serde_json::to_string(&entry).unwrap();
        let deserialized: ProfileEntry = serde_json::from_str(&json).unwrap();
        assert_eq!(entry.id, deserialized.id);
        assert!(deserialized.last_synced.is_some());
    }

    #[test]
    fn profile_source_serde_mitre() {
        let source = ProfileSource::Mitre;
        let json = serde_json::to_value(&source).unwrap();
        assert_eq!(json, "mitre");
        let deserialized: ProfileSource = serde_json::from_value(json).unwrap();
        assert_eq!(deserialized, ProfileSource::Mitre);
    }

    #[test]
    fn profile_source_serde_dev_sec() {
        let source = ProfileSource::DevSec;
        let json = serde_json::to_value(&source).unwrap();
        assert_eq!(json, "dev_sec");
        let deserialized: ProfileSource = serde_json::from_value(json).unwrap();
        assert_eq!(deserialized, ProfileSource::DevSec);
    }

    #[test]
    fn profile_source_serde_gcp() {
        let source = ProfileSource::Gcp;
        let json = serde_json::to_value(&source).unwrap();
        assert_eq!(json, "gcp");
        let deserialized: ProfileSource = serde_json::from_value(json).unwrap();
        assert_eq!(deserialized, ProfileSource::Gcp);
    }

    #[test]
    fn profile_source_serde_cis() {
        let source = ProfileSource::Cis;
        let json = serde_json::to_value(&source).unwrap();
        assert_eq!(json, "cis");
        let deserialized: ProfileSource = serde_json::from_value(json).unwrap();
        assert_eq!(deserialized, ProfileSource::Cis);
    }

    #[test]
    fn profile_source_serde_custom() {
        let source = ProfileSource::Custom;
        let json = serde_json::to_value(&source).unwrap();
        assert_eq!(json, "custom");
        let deserialized: ProfileSource = serde_json::from_value(json).unwrap();
        assert_eq!(deserialized, ProfileSource::Custom);
    }

    #[test]
    fn profile_source_serde_auto_generated() {
        let source = ProfileSource::AutoGenerated;
        let json = serde_json::to_value(&source).unwrap();
        assert_eq!(json, "auto_generated");
        let deserialized: ProfileSource = serde_json::from_value(json).unwrap();
        assert_eq!(deserialized, ProfileSource::AutoGenerated);
    }

    #[test]
    fn profile_source_display() {
        assert_eq!(ProfileSource::Mitre.to_string(), "mitre");
        assert_eq!(ProfileSource::DevSec.to_string(), "dev-sec");
        assert_eq!(ProfileSource::Gcp.to_string(), "gcp");
        assert_eq!(ProfileSource::Cis.to_string(), "cis");
        assert_eq!(ProfileSource::Custom.to_string(), "custom");
        assert_eq!(ProfileSource::AutoGenerated.to_string(), "auto-generated");
    }

    #[test]
    fn index_stats_empty() {
        let stats = IndexStats::empty();
        assert_eq!(stats.total_profiles, 0);
        assert_eq!(stats.total_controls, 0);
        assert_eq!(stats.total_rspec_generated, 0);
        assert!(stats.providers_covered.is_empty());
        assert!(stats.nist_families_covered.is_empty());
    }

    #[test]
    fn index_stats_serde_roundtrip() {
        let stats = IndexStats {
            total_profiles: 5,
            total_controls: 100,
            total_rspec_generated: 3,
            providers_covered: vec!["aws".to_string(), "gcp".to_string()],
            nist_families_covered: vec!["AC".to_string(), "CM".to_string()],
        };
        let json = serde_json::to_string(&stats).unwrap();
        let deserialized: IndexStats = serde_json::from_str(&json).unwrap();
        assert_eq!(stats, deserialized);
    }

    #[test]
    fn profile_entry_multiple_providers() {
        let mut entry = sample_entry();
        entry.applicable_providers = vec![
            "aws".to_string(),
            "gcp".to_string(),
            "azure".to_string(),
        ];
        let json = serde_json::to_string(&entry).unwrap();
        let deserialized: ProfileEntry = serde_json::from_str(&json).unwrap();
        assert_eq!(deserialized.applicable_providers.len(), 3);
    }

    #[test]
    fn profile_entry_empty_collections() {
        let entry = ProfileEntry {
            id: "empty".to_string(),
            name: "Empty".to_string(),
            source: ProfileSource::Custom,
            upstream_url: String::new(),
            upstream_ref: String::new(),
            control_count: 0,
            profile_hash: String::new(),
            applicable_providers: vec![],
            nist_families: vec![],
            cis_benchmarks: vec![],
            rspec_generated: false,
            last_synced: None,
        };
        let json = serde_json::to_string(&entry).unwrap();
        let deserialized: ProfileEntry = serde_json::from_str(&json).unwrap();
        assert_eq!(entry, deserialized);
    }

    #[test]
    fn profile_entry_with_cis_benchmarks() {
        let mut entry = sample_entry();
        entry.cis_benchmarks = vec![
            "CIS-1.1".to_string(),
            "CIS-2.3".to_string(),
        ];
        let json = serde_json::to_string(&entry).unwrap();
        let deserialized: ProfileEntry = serde_json::from_str(&json).unwrap();
        assert_eq!(deserialized.cis_benchmarks.len(), 2);
        assert_eq!(deserialized.cis_benchmarks[0], "CIS-1.1");
    }

    #[test]
    fn profile_entry_rspec_generated_flag() {
        let mut entry = sample_entry();
        entry.rspec_generated = true;
        let json = serde_json::to_string(&entry).unwrap();
        let deserialized: ProfileEntry = serde_json::from_str(&json).unwrap();
        assert!(deserialized.rspec_generated);
    }
}
